spring:
    application:
      name: profile
    profiles:
      active: dev
    jpa:
      open-in-view: false
notification:
  client:
    url: ${NOTIFICATION_CLIENT_URL}
lingosphinx:
    gamification:
      api-key: ${GAMIFICATION_API_KEY}