name: Habit Reset

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  wake-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up the app
        run: |
          echo "Waking up the Render app..."
          curl -s -H POST "X-Cron-Secret: ${{ secrets.CRON_SECRET_TOKEN }}" https://lingosphinx-gamification-api.onrender.com/schedule/habit/reset > /dev/null

      - name: Wait for app to wake
        run: |
          echo "Waiting for 60 seconds..."
          sleep 60

      - name: Call schedule endpoint
        run: |
          echo "Calling schedule endpoint..."
          curl -s -H POST "X-Cron-Secret: ${{ secrets.CRON_SECRET_TOKEN }}" https://lingosphinx-gamification-api.onrender.com/schedule/habit/reset
