# .github/workflows/habit-reset.yml
name: Habit Reset

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  wake-and-run:
    runs-on: ubuntu-latest
    env:
      REMOTE_BASE_URL: ${{ vars.REMOTE_BASE_URL }}
    steps:
      - name: Call schedule endpoint
        run: |
          echo "Calling schedule endpoint..."
          curl -s -X POST $REMOTE_BASE_URL/schedule/habit/reset -H "X-Cron-Secret: ${{ secrets.CRON_SECRET_TOKEN }}"